
	Test: add_test.py


..
----------------------------------------------------------------------
Ran 2 tests in 0.002s

OK

	Test: delete_test.py


..
----------------------------------------------------------------------
Ran 2 tests in 0.004s

OK

	Test: __init__.py


..
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK

	Test: read_all_test.py


..
----------------------------------------------------------------------
Ran 2 tests in 0.002s

OK

	Test: read_by_date_part_test.py


..
----------------------------------------------------------------------
Ran 2 tests in 0.003s

OK

	Test: read_head_test.py


..
----------------------------------------------------------------------
Ran 2 tests in 0.001s

OK

	Test: read_range_test.bk


..
----------------------------------------------------------------------
Ran 2 tests in 0.002s

OK

	Test: read_range_test.py


..
----------------------------------------------------------------------
Ran 2 tests in 0.002s

OK

	Test: read_search_rows_multi_column.py


..
----------------------------------------------------------------------
Ran 2 tests in 0.002s

OK

	Test: read_search_rows_test.py


..
----------------------------------------------------------------------
Ran 2 tests in 0.001s

OK

	Test: read_tail_test.py


..
----------------------------------------------------------------------
Ran 2 tests in 0.002s

OK

	Test: test-results


  File "test-results", line 2
    Test: add_test.py
    ^
IndentationError: unexpected indent

	Test: update_test.py


..
----------------------------------------------------------------------
Ran 2 tests in 0.002s

OK
